
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/svc_prom.yml
  - resources/pvc_prom.yml
  - resources/configmap_prom.yml
  - resources/deployment_prom.yml
  #test1